import housingTerrazaVacio from "../../public/Images/housingTerrazaVacio.webp"
import biblioteca from "../../public/Images/bibliotecaPortada.webp"
import biblioteca1 from "../../public/Images/julio2023biblioteca/ANAQUELESARRIBA-min.webp"
import biblioteca2 from "../../public/Images/julio2023biblioteca/ANAQUELESENTRADA-min.webp"
import biblioteca3 from "../../public/Images/julio2023biblioteca/AREADETRABAJO-min.webp"
import biblioteca4 from "../../public/Images/julio2023biblioteca/FONDO-min.webp"
import biblioteca5 from "../../public/Images/julio2023biblioteca/RECEPCION-min.webp"
import biblioteca6 from "../../public/Images/julio2023biblioteca/RECEPCION2-min.webp"
import biblioteca7 from "../../public/Images/julio2023biblioteca/RECEPCIONDESDEARRIBA-min.webp"
import biblioteca8 from "../../public/Images/julio2023biblioteca/LLEGADA-ESC-min.webp"
import biblioteca9 from "../../public/Images/julio2023biblioteca/TERRAZA-min.webp"
import biblioteca10 from "../../public/Images/julio2023biblioteca/VISTAENTREPISO-min.webp"
import biblioteca11 from "../../public/Images/julio2023biblioteca/PA-min.webp"
import biblioteca12 from "../../public/Images/julio2023biblioteca/PB-min.webp"
import biblioteca13 from "../../public/Images/julio2023biblioteca/CORTE-LONG-min.webp"
import biblioteca14 from "../../public/Images/julio2023biblioteca/CORTE-FUGADO-min.webp"
import biblioteca15 from "../../public/Images/julio2023biblioteca/AXO-min.webp"
import housing1 from "../../public/Images/julio2021/1.webp"
import housing2 from "../../public/Images/julio2021/2.webp"
import housing3 from "../../public/Images/julio2021/AXO.webp"
import housing4 from "../../public/Images/julio2021/P1.webp"
import housing5 from "../../public/Images/julio2021/p2.webp"
import housing6 from "../../public/Images/julio2021/p3.webp"
import housing7 from "../../public/Images/julio2021/p4.webp"
import housing8 from "../../public/Images/julio2021/p5.webp"
import housing9 from "../../public/Images/julio2021/p6.webp"
import housing10 from "../../public/Images/julio2021/p7.webp"
import housing11 from "../../public/Images/julio2021/p8.webp"
import housing12 from "../../public/Images/julio2021/p9.webp"
import housing13 from "../../public/Images/julio2021/p10.webp"
import housing14 from "../../public/Images/julio2021/p11.webp"
import housing15 from "../../public/Images/julio2021/p13.webp"
import densidad1 from "../../public/Images/julio2022/1.webp"
import densidad2 from "../../public/Images/julio2022/2.webp"
import densidad3 from "../../public/Images/julio2022/3.webp"
import densidad4 from "../../public/Images/julio2022/4.webp"
import densidad5 from "../../public/Images/julio2022/5.webp"
import densidad6 from "../../public/Images/julio2022/6.webp"
import densidad7 from "../../public/Images/julio2022/7.webp"
import densidad8 from "../../public/Images/julio2022/8.webp"
import densidad10 from "../../public/Images/julio2022/9.webp"
import densidad11 from "../../public/Images/julio2022/10.webp"
import densidad12 from "../../public/Images/julio2022/11.webp"
import densidad13 from "../../public/Images/julio2022/12.webp"
import densidad14 from "../../public/Images/julio2022/13.webp"
import densidad15 from "../../public/Images/julio2022/14.webp"
import densidad16 from "../../public/Images/julio2022/15.webp"
import densidad17 from "../../public/Images/julio2022/16.webp"
import densidad18 from "../../public/Images/julio2022/17.webp"
import densidad19 from "../../public/Images/julio2022/18.webp"
import densidad20 from "../../public/Images/julio2022/19.webp"
import densidad21 from "../../public/Images/julio2022/20.webp"
import densidad22 from "../../public/Images/julio2022/21.webp"
import densidad23 from "../../public/Images/julio2022/22.webp"
import densidad24 from "../../public/Images/julio2022/23.webp"
import densidad25 from "../../public/Images/julio2022/24.webp"
import densidad26 from "../../public/Images/julio2022/25.webp"
import intercambiador1 from "../../public/Images/julio2023intercambiador/A.webp"
import intercambiador2 from "../../public/Images/julio2023intercambiador/B.webp"
import intercambiador3 from "../../public/Images/julio2023intercambiador/C.webp"
import intercambiador4 from "../../public/Images/julio2023intercambiador/D1.webp"
import intercambiador5 from "../../public/Images/julio2023intercambiador/D2.webp"
import intercambiador6 from "../../public/Images/julio2023intercambiador/axogeneral.webp"
import intercambiador7 from "../../public/Images/julio2023intercambiador/AXO 2.webp"
import intercambiador8 from "../../public/Images/julio2023intercambiador/PA.webp"
import intercambiador9 from "../../public/Images/julio2023intercambiador/PB.webp"
import intercambiador10 from "../../public/Images/julio2023intercambiador/SS.webp"
import intercambiador11 from "../../public/Images/julio2023intercambiador/cortefugado.webp"
import intercambiador12 from "../../public/Images/julio2023intercambiador/D1.webp"
import intercambiador13 from "../../public/Images/julio2023intercambiador/D2.webp"
import intercambiador14 from "../../public/Images/julio2023intercambiador/despiece.webp"
import building1 from "../../public/Images/noviembre2021/RENDER2.webp"
import building2 from "../../public/Images/noviembre2021/PORTADA.webp"
import building3 from "../../public/Images/noviembre2021/PB.webp"
import building4 from "../../public/Images/noviembre2021/SS.webp"
import building5 from "../../public/Images/noviembre2021/1P.webp"
import building6 from "../../public/Images/noviembre2021/2P.webp"
import building7 from "../../public/Images/noviembre2021/3P.webp"
import building8 from "../../public/Images/noviembre2021/4P.webp"
import building9 from "../../public/Images/noviembre2021/5P.webp"
import building11 from "../../public/Images/noviembre2021/6P.webp"
import building12 from "../../public/Images/noviembre2021/CORTEBC.webp"
import building13 from "../../public/Images/noviembre2021/CORTEFACHADA.webp"
import building14 from "../../public/Images/noviembre2021/AXOCORTADA.webp"
import building15 from "../../public/Images/noviembre2021/ESTR.webp"
import building16 from "../../public/Images/noviembre2021/DETALLES.webp"
import building17 from "../../public/Images/noviembre2021/CIRC.webp"
import building18 from "../../public/Images/noviembre2021/PROGRAMA.webp"
import building19 from "../../public/Images/noviembre2021/4DA9D21D-7DF6-4E48-BEDF-2516134603ED.webp"
import building20 from "../../public/Images/noviembre2021/IMG_1939.webp"
import edificioPortada from "../../public/Images/edificioPortada.webp"
import intercambiadorPortada from "../../public/Images/intercambiadorPortada.webp"
import mercado from "../../public/Images/noviembre2022/50.webp"
import mercado1 from "../../public/Images/noviembre2022/51.webp"
import mercado2 from "../../public/Images/noviembre2022/52.webp"
import mercado3 from "../../public/Images/noviembre2022/53.webp"
import mercado4 from "../../public/Images/noviembre2022/54.webp"
import mercado5 from "../../public/Images/noviembre2022/55.webp"
import mercado6 from "../../public/Images/noviembre2022/pb.webp"
import mercado7 from "../../public/Images/noviembre2022/1p.webp"
import mercado8 from "../../public/Images/noviembre2022/2p.webp"
import mercado9 from "../../public/Images/noviembre2022/3p.webp"
import mercado10 from "../../public/Images/noviembre2022/4p.webp"
import mercado11 from "../../public/Images/noviembre2022/5p.webp"
import mercado12 from "../../public/Images/noviembre2022/6p.webp"
import mercado13 from "../../public/Images/noviembre2022/ss.webp"
import mercado14 from "../../public/Images/noviembre2022/plantaaudit.webp"
import mercado15 from "../../public/Images/noviembre2022/plani.webp"
import mercado16 from "../../public/Images/noviembre2022/1.webp"
import mercado17 from "../../public/Images/noviembre2022/2.webp"
import mercado18 from "../../public/Images/noviembre2022/3.webp"
import mercado19 from "../../public/Images/noviembre2022/4.webp"
import mercado20 from "../../public/Images/noviembre2022/5.webp"
import mercado21 from "../../public/Images/noviembre2022/6.webp"
import mercado22 from "../../public/Images/noviembre2022/7.webp"
import mercado23 from "../../public/Images/noviembre2022/8.webp"
import mercado24 from "../../public/Images/noviembre2022/9.webp"
import mercado25 from "../../public/Images/noviembre2022/10.webp"
import mercado26 from "../../public/Images/noviembre2022/11.webp"
import mercado27 from "../../public/Images/noviembre2022/12.webp"
import mercado28 from "../../public/Images/noviembre2022/13.webp"
import mercado29 from "../../public/Images/noviembre2022/14.webp"
import mercado30 from "../../public/Images/noviembre2022/15.webp"


export const items = [
    { id: 1, url:"housing",titulo: 'Minimum Housing',project:"",location:"Downtown Area, Córdoba, (Ar)",year:"2021",status:"Project",sector:"Housing", 
    imagenSrc: [housingTerrazaVacio,housing1,housing3,housing4,housing5,housing6,housing7,housing8,housing9,housing10,housing11,housing12,housing13,housing14,housing15] },
    { id: 2, url:"library",titulo: 'UNC Postgraduate Library',project:"",location:" Córdoba National University",year:"2023",status:"Project",sector:"Institutional", 
    imagenSrc: [biblioteca, biblioteca1,biblioteca2,biblioteca3,biblioteca4,biblioteca5,biblioteca6,biblioteca7,biblioteca8,biblioteca9,biblioteca10,biblioteca11,biblioteca12,biblioteca13,biblioteca14,biblioteca15]},
    { id: 3, url:"building",titulo: 'Residential Building',project:"",location:"Downtown Area, Córdoba, (Ar)",year:"2021",status:"Project",sector:"Residential", 
    imagenSrc: [edificioPortada,building1,building2,building3,building4,building5,building6,building7
    ,building8,building9,building11,building12,building13,building14,building15,building16,building17,building18,building19
    ,building20]},
    { id: 4, url:"intermodal",titulo: 'UNC Intermodal Station',project:"",location:"Córdoba National University",year:"2023",status:"Project",sector:"Intermodal Station", 
    imagenSrc: [intercambiadorPortada,intercambiador2,intercambiador3,intercambiador6
    ,intercambiador7,intercambiador9,intercambiador8,intercambiador10,intercambiador11,intercambiador12,intercambiador13
    ,intercambiador14 ]},
    { id: 5, url:"creativemarket",titulo: 'Creative Industries Market',project:"Córdoba Creative Industries Market",location:"General Paz, Córdoba, (Ar)",year:"2022",status:"Project",sector:"Public Buildings", 
    imagenSrc: [mercado,mercado1,mercado2,mercado3,mercado4,mercado5,mercado6,mercado7,mercado8
    ,mercado9,mercado10,mercado11,mercado12,mercado13,mercado14,mercado15,mercado16,mercado17,mercado18,mercado19
    ,mercado20,mercado21,mercado22,mercado23,mercado24,mercado25,mercado26,mercado27,mercado28,mercado29
    ,mercado30]},
    { id: 6, url:"void",titulo: 'The Density in the Void',project:"",location:"No Context",year:"2022",status:"Project",sector:"Exploration", 
    imagenSrc: [densidad1,densidad2,densidad3,densidad4,densidad5,densidad6,densidad7,
    densidad8,densidad10,densidad11,densidad12,densidad13,densidad14,densidad15,densidad16,densidad17,densidad18,densidad19,densidad20,densidad21,densidad22,
    densidad23,densidad24,densidad25,densidad26,
    ]},
  ];